task: convert_deepen_to_t4
description:
  visibility:
    full: "No occlusion of the object."
    most: "Object is occluded, but by less than 50%."
    partial: "The object is occluded by more than 50% (but not completely)."
    none: "The object is 90-100% occluded and no points/pixels are visible in the label."
  camera_index:
    CAM_FRONT: 0
    CAM_FRONT_RIGHT: 1
    CAM_BACK_RIGHT: 2
    CAM_BACK: 3
    CAM_BACK_LEFT: 4
    CAM_FRONT_LEFT: 5

conversion:
  input_base: ./data/komatsu005_non_annotated_t4_format
  input_anno_file: ./data/deepen_format/lidar_annotations_accepted_deepen2.json
  input_bag_base: ./data/komatsu005_rosbag2
  input_bag_file: ./data/komatsu005_rosbag2/komatsu005/2f9395c1-4faa-4907-8faf-e4543244ec9e_2023-12-15-11-12-39_concat_0.db3
  output_base: ./data/komatsu_t4_format
  topic_list: ./config/topic_list_sample.yaml
  ignore_interpolate_label: True
  dataset_corresponding:
    # komatsu005: jUqxAanejz5NVNVA8yRvmdRA
    # komatsu005: bBBBGGqg4thv1vqFCKiQVgGe
    komatsu_new_005: XometuhADxVXrvMKdQdg2178
